name: upr_lda
channels:
  - defaults
dependencies:
  - boost-cpp=1.82.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.2.25
  - cairo=1.16.0
  - expat=2.7.1
  - fontconfig=2.14.1
  - freetype=2.13.3
  - gettext=0.21.0
  - giflib=5.2.2
  - icu=73.1
  - jpeg=9e
  - krb5=1.20.1
  - lcms2=2.16
  - leptonica=1.82.0
  - lerc=4.0.0
  - libarchive=3.7.7
  - libboost=1.82.0
  - libcurl=8.12.1
  - libcxx=14.0.6
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libglib=2.78.4
  - libiconv=1.16
  - libnghttp2=1.57.0
  - libpng=1.6.39
  - libssh2=1.11.1
  - libtiff=4.7.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxml2=2.13.8
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - ncurses=6.4
  - nspr=4.35
  - nss=3.89.1
  - openjpeg=2.5.2
  - openssl=3.0.16
  - pcre2=10.42
  - pip=25.1
  - pixman=0.40.0
  - poppler=24.09.0
  - poppler-data=0.4.11
  - python=3.12.9
  - readline=8.2
  - setuptools=78.1.1
  - sqlite=3.45.3
  - tesseract=5.2.0
  - tk=8.6.14
  - tzdata=2025b
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.7
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - attrs==25.3.0
      - beautifulsoup4==4.13.4
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - cloudscraper==1.2.71
      - frozenlist==1.6.2
      - idna==3.10
      - iniconfig==2.1.0
      - lxml==6.0.0
      - multidict==6.4.4
      - packaging==25.0
      - pdf2image==1.17.0
      - pillow==11.2.1
      - pluggy==1.6.0
      - propcache==0.3.1
      - pydantic==2.11.5
      - pydantic-core==2.33.2
      - pygments==2.19.1
      - pyparsing==3.2.3
      - pytesseract==0.3.13
      - pytest==8.4.0
      - pytest-asyncio==1.0.0
      - python-dotenv==1.1.1
      - requests==2.32.4
      - requests-toolbelt==1.0.0
      - soupsieve==2.7
      - typing-extensions==4.14.0
      - typing-inspection==0.4.1
      - unidecode==1.4.0
      - urllib3==2.5.0
      - yarl==1.20.0
